"""add document signatures

Revision ID: 1ffdbd9308d7
Revises: e832dcd9123f
Create Date: 2026-08-31 13:40:24.564981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffdbd9308d7'
down_revision: Union[str, Sequence[str], None] = 'e832dcd9123f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('key_label', sa.String(length=100), nullable=False),
    sa.Column('signature_base64', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['authentication_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_document_signature_session')
    )
    op.create_index(op.f('ix_document_signatures_device_id'), 'document_signatures', ['device_id'], unique=False)
    op.create_index(op.f('ix_document_signatures_document_id'), 'document_signatures', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_signatures_session_id'), 'document_signatures', ['session_id'], unique=False)
    op.create_index(op.f('ix_document_signatures_user_id'), 'document_signatures', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_signatures_user_id'), table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_session_id'), table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_document_id'), table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_device_id'), table_name='document_signatures')
    op.drop_table('document_signatures')
    # ### end Alembic commands ###
