"""add persistent used nonces

Revision ID: 3f66ae3a6333
Revises: 495bafdef61d
Create Date: 2026-08-26 15:22:09.631168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f66ae3a6333'
down_revision: Union[str, Sequence[str], None] = '495bafdef61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_nonces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'nonce', name='uq_used_nonce_device_nonce')
    )
    op.create_index(op.f('ix_used_nonces_expires_at'), 'used_nonces', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_used_nonces_expires_at'), table_name='used_nonces')
    op.drop_table('used_nonces')
    # ### end Alembic commands ###
