"""add authentication credentials and sessions

Revision ID: 495bafdef61d
Revises: 8e42683cef4a
Create Date: 2026-08-26 10:37:12.914030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495bafdef61d'
down_revision: Union[str, Sequence[str], None] = '8e42683cef4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentication_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('rfid_uid', sa.String(length=100), nullable=False),
    sa.Column('fingerprint_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'fingerprint_id', name='uq_auth_credential_device_fingerprint'),
    sa.UniqueConstraint('device_id', 'rfid_uid', name='uq_auth_credential_device_rfid')
    )
    op.create_index(op.f('ix_authentication_credentials_device_id'), 'authentication_credentials', ['device_id'], unique=False)
    op.create_index(op.f('ix_authentication_credentials_rfid_uid'), 'authentication_credentials', ['rfid_uid'], unique=False)
    op.create_index(op.f('ix_authentication_credentials_user_id'), 'authentication_credentials', ['user_id'], unique=False)
    op.create_table('authentication_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rfid_uid', sa.String(length=100), nullable=False),
    sa.Column('challenge', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authentication_sessions_challenge'), 'authentication_sessions', ['challenge'], unique=True)
    op.create_index(op.f('ix_authentication_sessions_device_id'), 'authentication_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_authentication_sessions_user_id'), 'authentication_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authentication_sessions_user_id'), table_name='authentication_sessions')
    op.drop_index(op.f('ix_authentication_sessions_device_id'), table_name='authentication_sessions')
    op.drop_index(op.f('ix_authentication_sessions_challenge'), table_name='authentication_sessions')
    op.drop_table('authentication_sessions')
    op.drop_index(op.f('ix_authentication_credentials_user_id'), table_name='authentication_credentials')
    op.drop_index(op.f('ix_authentication_credentials_rfid_uid'), table_name='authentication_credentials')
    op.drop_index(op.f('ix_authentication_credentials_device_id'), table_name='authentication_credentials')
    op.drop_table('authentication_credentials')
    # ### end Alembic commands ###
