"""bind authentication session to document

Revision ID: 5ab911154637
Revises: 3f66ae3a6333
Create Date: 2026-08-26 16:54:44.047544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab911154637'
down_revision: Union[str, Sequence[str], None] = '3f66ae3a6333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentication_sessions', sa.Column('document_hash', sa.String(length=64), nullable=True))
    op.add_column('authentication_sessions', sa.Column('decision', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_authentication_sessions_document_hash'), 'authentication_sessions', ['document_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authentication_sessions_document_hash'), table_name='authentication_sessions')
    op.drop_column('authentication_sessions', 'decision')
    op.drop_column('authentication_sessions', 'document_hash')
    # ### end Alembic commands ###
