"""add security audit events

Revision ID: 6e154e02cecf
Revises: 1ffdbd9308d7
Create Date: 2026-08-31 14:05:06.053754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e154e02cecf'
down_revision: Union[str, Sequence[str], None] = '1ffdbd9308d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('signature_id', sa.UUID(), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['authentication_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signature_id'], ['document_signatures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_audit_events_created_at'), 'security_audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_audit_events_device_id'), 'security_audit_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_security_audit_events_document_id'), 'security_audit_events', ['document_id'], unique=False)
    op.create_index(op.f('ix_security_audit_events_event_type'), 'security_audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_events_outcome'), 'security_audit_events', ['outcome'], unique=False)
    op.create_index(op.f('ix_security_audit_events_session_id'), 'security_audit_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_security_audit_events_signature_id'), 'security_audit_events', ['signature_id'], unique=False)
    op.create_index(op.f('ix_security_audit_events_user_id'), 'security_audit_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_audit_events_user_id'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_signature_id'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_session_id'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_outcome'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_event_type'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_document_id'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_device_id'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_created_at'), table_name='security_audit_events')
    op.drop_table('security_audit_events')
    # ### end Alembic commands ###
