"""add device authentication secret

Revision ID: 8e42683cef4a
Revises: ddab53bf6ab2
Create Date: 2026-07-25 13:42:32.209903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e42683cef4a'
down_revision: Union[str, Sequence[str], None] = 'ddab53bf6ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_secret', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'device_secret')
    # ### end Alembic commands ###
