"""link authentication session to document

Revision ID: e832dcd9123f
Revises: 5c395d25ad1a
Create Date: 2026-08-27 18:58:10.492289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e832dcd9123f'
down_revision: Union[str, Sequence[str], None] = '5c395d25ad1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentication_sessions', sa.Column('document_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_authentication_sessions_document_id'), 'authentication_sessions', ['document_id'], unique=False)
    op.create_foreign_key(None, 'authentication_sessions', 'documents', ['document_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authentication_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_authentication_sessions_document_id'), table_name='authentication_sessions')
    op.drop_column('authentication_sessions', 'document_id')
    # ### end Alembic commands ###
